### ISSUE TITLE
Relative URL warning in middleware

### ISSUE THREAD

**Issue by viperfx** [vercel/platforms#48]
This is currently the following warning when running the server

`warn  - using relative URLs for Middleware will be deprecated soon - https://nextjs.org/docs/messages/middleware-relative-urls`

**Comment by NuroDev** [comment]
I believe this was fixed in https://github.com/vercel/platforms/commit/dc72ef376078be18dec8345dbdba9d9e82e1f9b1

**Comment by tylerjharden** [comment]
Since it has now been removed the `NextResponse.redirect("/")` now throws an error, so not fully fixed.
